# These are supported funding model platforms

github: [ idmarinas ] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: idmarinas # Replace with a single Patreon username
# ko_fi: idmarinas # Replace with a single Ko-fi username
# liberapay: idmarinas # Replace with a single Liberapay username
custom: [ 'https://www.paypal.me/idmarinas' ] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
