when@dev: &dev
    services:
        Core\Tests\DataFixtures\:
            resource: '%kernel.project_dir%/tests/DataFixtures/'
            autowire: true
            autoconfigure: true

when@test: *dev
