when@dev: &dev
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        Core\Tests\DataFixtures\:
            resource: '%kernel.project_dir%/tests/DataFixtures/'

when@test: *dev
