framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(APP_MAILER_ADDRESS_FROM)%'
        headers:
            From: '%env(APP_MAILER_ADDRESS_FROM_NAME)% <%env(APP_MAILER_ADDRESS_FROM)%>'
