monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - csp
    handlers:
        deprecation:
            type: stream
            channels: [ deprecation ]
            path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
        csp:
            type: stream
            channels: [ csp ]
            path: '%kernel.logs_dir%/%kernel.environment%.csp.log'
        security:
            type: stream
            channels: [ security ]
            path: '%kernel.logs_dir%/%kernel.environment%.security.log'
        console:
            type: console
            process_psr_3_messages: false
            channels: [ console ]
            path: '%kernel.logs_dir%/%kernel.environment%.console.log'
        doctrine:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.doctrine.log'
            channels: [ doctrine ]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event", "!deprecation", "!security", "!doctrine", "!console", "!csp" ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
