security:
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Admin
        -   path: ^/%app.route_prefix.admin%/(login|logout)$
            host: ^admin\.%app.server_name.regexp%$
            roles: PUBLIC_ACCESS
        - { path: ^/%app.route_prefix.admin%(|/.*)$, host: ^admin\.%app.server_name.regexp%$, roles: ROLE_ADMIN }

        # The main route is public always
        - { path: ^/(|nelmio/csp/report)$, roles: PUBLIC_ACCESS }

        # Public pages
        - { path: ^/%app.route_prefix.public%(|/.*)$, roles: PUBLIC_ACCESS }

        # Routes for User
        - { path: ^/user/(token|login/web|connect)$, roles: PUBLIC_ACCESS }
        - { path: ^/user/registration/(register|verify/email)$, roles: PUBLIC_ACCESS }
        - { path: ^/user/reset-password/reset(|/[ ^\/. ]++)$, roles: PUBLIC_ACCESS }
        - { path: ^/user/reset-password(|/check-email)$, roles: PUBLIC_ACCESS }
        - { path: ^/user/.*$, roles: ROLE_USER }

        # By default, all routes that do not meet the above requirements are marked as private to avoid problems.
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
