# yaml-language-server: $schema=../../vendor/symfony/security-bundle/Resources/config/schema/security-1.0.xsd

security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        # Admin Firewall
        admin:
            lazy: true
            stateless: false
            host: '^admin\.%app.server_name.regexp%$'
            provider: users_in_memory
            switch_user: false
            form_login:
                enable_csrf: true
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin_dashboard
            logout:
                path: '/%app.route_prefix.admin%/logout'
                target: admin_login
                enable_csrf: true
                clear_site_data:
                    - cache
                    - cookies
                    - executionContexts
                    - storage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false
                secure: true
                signature_properties: [ 'password', 'updatedAt', 'deletedAt' ]
        # Main Firewall
        main:
            lazy: true
            stateless: false
            provider: app_user_provider
            switch_user: false
            user_checker: App\Security\Checker\UserChecker
            form_login:
                #login_path: user_login
                #check_path: user_login
                default_target_path: app_home
                enable_csrf: true
            logout:
                path: /logout
                target: app_home
                enable_csrf: true
                clear_site_data:
                    - cookies
                    - storage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false
                secure: true
                #signature_properties: [ 'password', 'updatedAt', 'deletedAt', 'bannedUntil' ]

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html

when@dev: &dev
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

when@test: *dev
