security:
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Main route is public always
        - { path: ^/(|nelmio/csp/report)$, roles: PUBLIC_ACCESS }

        # Routes to Panels
        # Admin
        - { path: '^/panel/%app.route_prefix.admin%/(login|logout)$', roles: PUBLIC_ACCESS }
        - { path: '^/panel/%app.route_prefix.admin%(|/.)$', roles: ROLE_ADMIN }
        # Others
        - { path: '^/panel(|/.)$', roles: ROLE_ADMIN }

        # Routes for User
        - { path: '^/%app.route_prefix.user%/(token|login/web|connect)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/registration/(register|verify/email)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/reset-password/reset(|/[^\/.]++)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/reset-password(|/check-email)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%', roles: ROLE_USER }

        # By default, all routes that do not meet the above requirements are marked as private to avoid problems.
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
