security:
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Routes to Panels
        # Admin
        - { path: '^/%app.route_prefix.admin%/(login|logout)$', host: ^admin.localhost$, roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.admin%(|/.*)$', host: ^admin.localhost$, roles: ROLE_ADMIN }
        # Others
        - { path: '^/panel(|/.)$', host: ^admin.localhost$, roles: ROLE_ADMIN }

        # Main route is public always
        - { path: ^/(|nelmio/csp/report)$, roles: PUBLIC_ACCESS }

        # Public pages
        - { path: '^/%app.route_prefix.public%(|/.*)$', roles: PUBLIC_ACCESS }

        # Routes for User
        - { path: '^/%app.route_prefix.user%/(token|login/web|connect)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/registration/(register|verify/email)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/reset-password/reset(|/[^\/.]++)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/reset-password(|/check-email)$', roles: PUBLIC_ACCESS }
        - { path: '^/%app.route_prefix.user%/.*$', roles: ROLE_USER }

        # By default, all routes that do not meet the above requirements are marked as private to avoid problems.
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
