twig:
    file_name_pattern: '*.twig'
    paths:
        'apps/admin/templates': Admin
        'apps/web/templates': Web
    form_themes:
        - 'forms/tailwind_3_layout.html.twig'
    globals:
        app_version: '%env(APP_VERSION)%'

when@test:
    twig:
        strict_variables: true
