twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        # Namespace & directory for components
        Shared\Twig\Components\: 'components/'
        Admin\Twig\Components\: 'apps/admin/templates/components/'
        Web\Twig\Components\: 'apps/web/templates/components/'
