services:
  ###> doctrine/doctrine-bundle ###
  database:
    restart: no
    ports:
      - "13306:3306"
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}_dev
      MARIADB_USER: ${DATABASE_USER}_dev
    volumes:
      - database_data_dev:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  database_test:
    restart: no
    extends:
      file: compose.yaml
      service: database
    ports: !reset [ ]
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}_test
      MARIADB_USER: ${DATABASE_USER}_test
    volumes:
      - database_data_test:/var/lib/mysql

  webserver:
    restart: no
    image: idmarinas/template-symfony:${APP_VERSION}-dev
    privileged: true
    volumes:
      - ./:/app
      - docker_dev_data:/var/lib/docker
      ## SSH
      - ssh_key:/root/.ssh
    depends_on: !override
      - database
      - database_test
      - mailer

  ###> symfony/mailer ###
  mailer:
    restart: no
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

volumes:
  database_data_dev:
  database_data_test:
  docker_dev_data:
  ssh_key:
    external: true
