services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.4.4
    ports:
      - "3316:3306"
    environment:
      # P^robar usando - y no _
      MARIADB_AUTO_UPGRADE: true
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      # MARIADB_RANDOM_ROOT_PASSWORD: 0
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql
    secrets:
      - db_password
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

secrets:
  db_password:
    environment: DATABASE_PASSWORD
