name: template_symfony

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.8.2
    ports:
      - "13306:3306"
    environment:
      MARIADB_AUTO_UPGRADE: true
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql
    secrets:
      - db_password
  ###< doctrine/doctrine-bundle ###

  caddy:
    image: idmarinas/caddy:2.10
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
    environment:
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
    volumes:
      # Project files
      - ./:/srv
      # Global config
      - .docker/caddy/globals/prod.Caddyfile:/etc/caddy/globals/Caddyfile:ro
      # Config
      - .docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      # Snippets
      - .docker/caddy/snippets/sites.Caddyfile:/etc/caddy/snippets/sites.Caddyfile:ro
      - .docker/caddy/snippets/prod.Caddyfile:/etc/caddy/snippets/Caddyfile:ro
      # Sites
      - .docker/caddy/sites:/etc/caddy/sites:ro
      # Named volumes for /data and /config to persist important information.
      - caddy_data:/data
      - caddy_config:/config
    secrets:
      - cloudflare_api_token
    depends_on:
      - php
      - database

  php:
    image: idmarinas/php:8.4
    healthcheck:
      test: php -v || exit 1
    volumes:
      - ./:/var/www/html
      ## PHP Conf
      - ./.docker/php/conf.d/date_timezone.ini:/usr/local/etc/php/conf.d/date_timezone.ini:ro

volumes:
  caddy_data:
  caddy_config:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

secrets:
  db_password:
    environment: DATABASE_PASSWORD
  cloudflare_api_token:
    environment: CLOUDFLARE_API_TOKEN
