services:
  database:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5s

  webserver:
    restart: always
    volumes:
      # Shared files between deployments
      - source_uploads:/app/public/uploads # For example, files uploaded by users
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 5s

  messenger_worker_async:
    image: idmarinas/template-symfony:${APP_VERSION}
    entrypoint: '/usr/local/bin/msn_async_entrypoint.sh'
    restart: always
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M


  messenger_worker_scheduler:
    image: idmarinas/template-symfony:${APP_VERSION}
    entrypoint: '/usr/local/bin/msn_scheduler_entrypoint.sh'
    restart: always
    healthcheck:
      test: [ "CMD", "php", "bin/console", "about" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - scheduler_cache:/app/var/scheduler
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

volumes:
  source_uploads:
  scheduler_cache:
