services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.4.5-ubi
    ports:
      - "3316:3306"
    environment:
      MARIADB_AUTO_UPGRADE: true
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      # MARIADB_RANDOM_ROOT_PASSWORD: 0
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql
    secrets:
      - db_password
  ###< doctrine/doctrine-bundle ###

  apache:
    image: idmarinas/apache:2.4
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
    depends_on:
      - php
      - database
    volumes:
      ## Config
      - ./.docker/apache/sites/common.conf:/usr/local/apache2/conf/sites/common.conf:ro

  php:
    image: idmarinas/php:8.4
    healthcheck:
      test: php -v || exit 1
    volumes:
      ## PHP Conf
      - ./.docker/php/conf.d/date_timezone.ini:/usr/local/etc/php/conf.d/date_timezone.ini:ro

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

secrets:
  db_password:
    environment: DATABASE_PASSWORD
