name: template_symfony

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${DATABASE_VERSION_NUMBER}
    environment:
      MARIADB_AUTO_UPGRADE: true
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - database_data:/var/lib/mysql
    secrets:
      - db_password
  ###< doctrine/doctrine-bundle ###

  webserver:
    image: idmarinas/template-symfony:${APP_VERSION}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: ${APP_SERVER_NAME}
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
    volumes:
      # Named volumes for /data and /config to persist important information.
      - caddy_data:/data
      - caddy_config:/config
    secrets:
      - cloudflare_api_token
    tty: true
    depends_on:
      - database

volumes:
  caddy_data:
  caddy_config:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

secrets:
  db_password:
    environment: DATABASE_PASSWORD
  cloudflare_api_token:
    environment: CLOUDFLARE_API_TOKEN
