name: template_symfony

services:
  ###> doctrine/doctrine-bundle ###
  database:
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}_dev
      MARIADB_USER: ${DATABASE_USER}_dev
    volumes:
      - database_data_dev:/var/lib/mysql

  database_test:
    extends:
      file: compose.yaml
      service: database
    ports: !reset [ ]
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}_test
      MARIADB_USER: ${DATABASE_USER}_test
    volumes:
      - database_data_test:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  apache:
    ports:
      - "8080:80"
      - "8083:443"
    volumes:
      - ./:/var/www/html
      ## Certs
      - ./.docker/apache/conf/localhost.crt:/usr/local/apache2/conf/localhost.crt:ro
      - ./.docker/apache/conf/localhost.key:/usr/local/apache2/conf/localhost.key:ro
      ## Sites
      - ./.docker/apache/sites/dev/000-default.conf:/usr/local/apache2/conf/sites/000-default.conf:ro
      - ./.docker/apache/sites/dev/default-ssl.conf:/usr/local/apache2/conf/sites/default-ssl.conf:ro
    depends_on:
      - php
      - database
      - database_test

  php:
    image: idmarinas/php:8.4-xdebug
    volumes:
      - ./:/var/www/html
      ## SSH
      - .docker/php/key_ssh/id_rsa:/root/.ssh/id_rsa:ro

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

volumes:
  database_data_dev:
  database_data_test:
