_security_logout:
    resource: security.route_loader.logout
    type: service

app_logout_admin:
    path: /panel/%app.route_prefix.admin%/logout
    methods: GET

app_logout_user:
    path: /%app.route_prefix.user%/logout
    methods: GET
