admin_controllers:
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    type: easyadmin.routes
    prefix: /panel
    name_prefix: app_panel_

user_controllers:
    resource:
        path: ../src/Controller/User
        namespace: App\Controller\User
    type: attribute
    prefix: '%app.route_prefix.user%'
    name_prefix: idm_user_
